// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsy9FDb9X1PAehW3s2kJNsovI3CG63cp0',
    appId: '1:232507166309:web:aa1ed93beda032fcc4008c',
    messagingSenderId: '232507166309',
    projectId: 'goals-gamification-app',
    authDomain: 'goals-gamification-app.firebaseapp.com',
    storageBucket: 'goals-gamification-app.firebasestorage.app',
    measurementId: 'G-B3Y3PTYVLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe1P5pKyKkuZw1Nc2iFgUSsyvw7m9Y18I',
    appId: '1:232507166309:android:96ced7035369e057c4008c',
    messagingSenderId: '232507166309',
    projectId: 'goals-gamification-app',
    storageBucket: 'goals-gamification-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN96Owm7myAC1fDjn3z7nBpauH_GDxCuQ',
    appId: '1:232507166309:ios:db38ca0e5dc58016c4008c',
    messagingSenderId: '232507166309',
    projectId: 'goals-gamification-app',
    storageBucket: 'goals-gamification-app.firebasestorage.app',
    iosBundleId: 'com.example.goalsGamificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN96Owm7myAC1fDjn3z7nBpauH_GDxCuQ',
    appId: '1:232507166309:ios:db38ca0e5dc58016c4008c',
    messagingSenderId: '232507166309',
    projectId: 'goals-gamification-app',
    storageBucket: 'goals-gamification-app.firebasestorage.app',
    iosBundleId: 'com.example.goalsGamificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsy9FDb9X1PAehW3s2kJNsovI3CG63cp0',
    appId: '1:232507166309:web:5d60f1914b601fc4c4008c',
    messagingSenderId: '232507166309',
    projectId: 'goals-gamification-app',
    authDomain: 'goals-gamification-app.firebaseapp.com',
    storageBucket: 'goals-gamification-app.firebasestorage.app',
    measurementId: 'G-CK7N2ECSX3',
  );

}